name: rlvenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - cvxpy
  - dill
  - matplotlib
  - numpy
  - ipykernel
  - ipympl
  - ipywidgets
  - seaborn
  - pip
  - pip:
    - pettingzoo
    - gymnasium